version: "3.8"

services:
  lgtm:
    image: docker.io/grafana/otel-lgtm:latest  # or specify a tag like 'v1.0.0'
    container_name: lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    environment:
      GF_PATHS_DATA: /data/grafana
    env_file:
      - .env
    volumes:
      - ./container/grafana:/data/grafana
      - ./container/prometheus:/data/prometheus
      - ./container/loki:/data/loki
    restart: unless-stopped
